// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: parquet/options.proto

package pbparquet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ColumnType int32

const (
	ColumnType_UNSPECIFIED_COLUMN_TYPE ColumnType = 0
	ColumnType_UINT256                 ColumnType = 1
	ColumnType_INT256                  ColumnType = 2
)

// Enum value maps for ColumnType.
var (
	ColumnType_name = map[int32]string{
		0: "UNSPECIFIED_COLUMN_TYPE",
		1: "UINT256",
		2: "INT256",
	}
	ColumnType_value = map[string]int32{
		"UNSPECIFIED_COLUMN_TYPE": 0,
		"UINT256":                 1,
		"INT256":                  2,
	}
)

func (x ColumnType) Enum() *ColumnType {
	p := new(ColumnType)
	*p = x
	return p
}

func (x ColumnType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ColumnType) Descriptor() protoreflect.EnumDescriptor {
	return file_parquet_options_proto_enumTypes[0].Descriptor()
}

func (ColumnType) Type() protoreflect.EnumType {
	return &file_parquet_options_proto_enumTypes[0]
}

func (x ColumnType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ColumnType.Descriptor instead.
func (ColumnType) EnumDescriptor() ([]byte, []int) {
	return file_parquet_options_proto_rawDescGZIP(), []int{0}
}

type Compression int32

const (
	Compression_UNCOMPRESSED Compression = 0
	Compression_SNAPPY       Compression = 1
	Compression_GZIP         Compression = 2
	Compression_LZ4_RAW      Compression = 3
	Compression_BROTLI       Compression = 4
	Compression_ZSTD         Compression = 5
)

// Enum value maps for Compression.
var (
	Compression_name = map[int32]string{
		0: "UNCOMPRESSED",
		1: "SNAPPY",
		2: "GZIP",
		3: "LZ4_RAW",
		4: "BROTLI",
		5: "ZSTD",
	}
	Compression_value = map[string]int32{
		"UNCOMPRESSED": 0,
		"SNAPPY":       1,
		"GZIP":         2,
		"LZ4_RAW":      3,
		"BROTLI":       4,
		"ZSTD":         5,
	}
)

func (x Compression) Enum() *Compression {
	p := new(Compression)
	*p = x
	return p
}

func (x Compression) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Compression) Descriptor() protoreflect.EnumDescriptor {
	return file_parquet_options_proto_enumTypes[1].Descriptor()
}

func (Compression) Type() protoreflect.EnumType {
	return &file_parquet_options_proto_enumTypes[1]
}

func (x Compression) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Compression.Descriptor instead.
func (Compression) EnumDescriptor() ([]byte, []int) {
	return file_parquet_options_proto_rawDescGZIP(), []int{1}
}

type Column struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Not implemented yet but planned so we reserved the field id now
	// optional string name = 1;
	Type          *ColumnType  `protobuf:"varint,2,opt,name=type,proto3,enum=parquet.ColumnType,oneof" json:"type,omitempty"`
	Compression   *Compression `protobuf:"varint,3,opt,name=compression,proto3,enum=parquet.Compression,oneof" json:"compression,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Column) Reset() {
	*x = Column{}
	mi := &file_parquet_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Column) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Column) ProtoMessage() {}

func (x *Column) ProtoReflect() protoreflect.Message {
	mi := &file_parquet_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Column.ProtoReflect.Descriptor instead.
func (*Column) Descriptor() ([]byte, []int) {
	return file_parquet_options_proto_rawDescGZIP(), []int{0}
}

func (x *Column) GetType() ColumnType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ColumnType_UNSPECIFIED_COLUMN_TYPE
}

func (x *Column) GetCompression() Compression {
	if x != nil && x.Compression != nil {
		return *x.Compression
	}
	return Compression_UNCOMPRESSED
}

var file_parquet_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         14756842,
		Name:          "parquet.table_name",
		Tag:           "bytes,14756842,opt,name=table_name",
		Filename:      "parquet/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         548935,
		Name:          "parquet.ignored",
		Tag:           "varint,548935,opt,name=ignored",
		Filename:      "parquet/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*Column)(nil),
		Field:         548936,
		Name:          "parquet.column",
		Tag:           "bytes,548936,opt,name=column",
		Filename:      "parquet/options.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// As long as table_name is not blank,
	// a schema is generated for top-level messages in each file.
	//
	// optional string table_name = 14756842;
	E_TableName = &file_parquet_options_proto_extTypes[0]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional bool ignored = 548935;
	E_Ignored = &file_parquet_options_proto_extTypes[1]
	// optional parquet.Column column = 548936;
	E_Column = &file_parquet_options_proto_extTypes[2]
)

var File_parquet_options_proto protoreflect.FileDescriptor

const file_parquet_options_proto_rawDesc = "" +
	"\n" +
	"\x15parquet/options.proto\x12\aparquet\x1a google/protobuf/descriptor.proto\"\x8c\x01\n" +
	"\x06Column\x12,\n" +
	"\x04type\x18\x02 \x01(\x0e2\x13.parquet.ColumnTypeH\x00R\x04type\x88\x01\x01\x12;\n" +
	"\vcompression\x18\x03 \x01(\x0e2\x14.parquet.CompressionH\x01R\vcompression\x88\x01\x01B\a\n" +
	"\x05_typeB\x0e\n" +
	"\f_compression*B\n" +
	"\n" +
	"ColumnType\x12\x1b\n" +
	"\x17UNSPECIFIED_COLUMN_TYPE\x10\x00\x12\v\n" +
	"\aUINT256\x10\x01\x12\n" +
	"\n" +
	"\x06INT256\x10\x02*X\n" +
	"\vCompression\x12\x10\n" +
	"\fUNCOMPRESSED\x10\x00\x12\n" +
	"\n" +
	"\x06SNAPPY\x10\x01\x12\b\n" +
	"\x04GZIP\x10\x02\x12\v\n" +
	"\aLZ4_RAW\x10\x03\x12\n" +
	"\n" +
	"\x06BROTLI\x10\x04\x12\b\n" +
	"\x04ZSTD\x10\x05:A\n" +
	"\n" +
	"table_name\x12\x1f.google.protobuf.MessageOptions\x18\xeaׄ\a \x01(\tR\ttableName:9\n" +
	"\aignored\x12\x1d.google.protobuf.FieldOptions\x18\xc7\xc0! \x01(\bR\aignored:K\n" +
	"\x06column\x12\x1d.google.protobuf.FieldOptions\x18\xc8\xc0! \x01(\v2\x0f.parquet.ColumnR\x06column\x88\x01\x01B\x9c\x01\n" +
	"\vcom.parquetB\fOptionsProtoP\x01ZCgithub.com/streamingfast/substreams-sink-files/pb/parquet;pbparquet\xa2\x02\x03PXX\xaa\x02\aParquet\xca\x02\aParquet\xe2\x02\x13Parquet\\GPBMetadata\xea\x02\aParquetb\x06proto3"

var (
	file_parquet_options_proto_rawDescOnce sync.Once
	file_parquet_options_proto_rawDescData []byte
)

func file_parquet_options_proto_rawDescGZIP() []byte {
	file_parquet_options_proto_rawDescOnce.Do(func() {
		file_parquet_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_parquet_options_proto_rawDesc), len(file_parquet_options_proto_rawDesc)))
	})
	return file_parquet_options_proto_rawDescData
}

var file_parquet_options_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_parquet_options_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_parquet_options_proto_goTypes = []any{
	(ColumnType)(0),                     // 0: parquet.ColumnType
	(Compression)(0),                    // 1: parquet.Compression
	(*Column)(nil),                      // 2: parquet.Column
	(*descriptorpb.MessageOptions)(nil), // 3: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 4: google.protobuf.FieldOptions
}
var file_parquet_options_proto_depIdxs = []int32{
	0, // 0: parquet.Column.type:type_name -> parquet.ColumnType
	1, // 1: parquet.Column.compression:type_name -> parquet.Compression
	3, // 2: parquet.table_name:extendee -> google.protobuf.MessageOptions
	4, // 3: parquet.ignored:extendee -> google.protobuf.FieldOptions
	4, // 4: parquet.column:extendee -> google.protobuf.FieldOptions
	2, // 5: parquet.column:type_name -> parquet.Column
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	5, // [5:6] is the sub-list for extension type_name
	2, // [2:5] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_parquet_options_proto_init() }
func file_parquet_options_proto_init() {
	if File_parquet_options_proto != nil {
		return
	}
	file_parquet_options_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_parquet_options_proto_rawDesc), len(file_parquet_options_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_parquet_options_proto_goTypes,
		DependencyIndexes: file_parquet_options_proto_depIdxs,
		EnumInfos:         file_parquet_options_proto_enumTypes,
		MessageInfos:      file_parquet_options_proto_msgTypes,
		ExtensionInfos:    file_parquet_options_proto_extTypes,
	}.Build()
	File_parquet_options_proto = out.File
	file_parquet_options_proto_goTypes = nil
	file_parquet_options_proto_depIdxs = nil
}
