// @generated
// This file is @generated by prost-build.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ColumnType {
    UnspecifiedColumnType = 0,
    Uint256 = 1,
    Int256 = 2,
}
impl ColumnType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            ColumnType::UnspecifiedColumnType => "UNSPECIFIED_COLUMN_TYPE",
            ColumnType::Uint256 => "UINT256",
            ColumnType::Int256 => "INT256",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNSPECIFIED_COLUMN_TYPE" => Some(Self::UnspecifiedColumnType),
            "UINT256" => Some(Self::Uint256),
            "INT256" => Some(Self::Int256),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TimestampType {
    UnspecifiedTimestampType = 0,
    TimestampMillis = 1,
    TimestampMicros = 2,
    TimestampNanos = 3,
}
impl TimestampType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            TimestampType::UnspecifiedTimestampType => "UNSPECIFIED_TIMESTAMP_TYPE",
            TimestampType::TimestampMillis => "TIMESTAMP_MILLIS",
            TimestampType::TimestampMicros => "TIMESTAMP_MICROS",
            TimestampType::TimestampNanos => "TIMESTAMP_NANOS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNSPECIFIED_TIMESTAMP_TYPE" => Some(Self::UnspecifiedTimestampType),
            "TIMESTAMP_MILLIS" => Some(Self::TimestampMillis),
            "TIMESTAMP_MICROS" => Some(Self::TimestampMicros),
            "TIMESTAMP_NANOS" => Some(Self::TimestampNanos),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
