// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: sf/substreams/sink/files/v1/files.proto

// The `sf.substreams.sink.files.v1` package can be use in your Substreams to defined a `map` module
// whose output type will be one of the message defined in the package. The `substreams-sink-files`
// binary will then consume your module's output to create the files containing your extracted data.
//
// The current package supports a single output format which is the `Lines` message which represents
// a list of plain-text "line" that should be appended together in a single bundle.

package pbsinkfiles

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Lines represents an ordered list of lines that have been extracted of a single block. You are
// free to format each line as you please, the `substream-sink-files` tool does not make any
// assumption about the content and simply write the content to the current bundle with a trailing
// new line.
//
// It is expected that your line do **not** contain a new line character as it will be managed
// manually by the `substream-sink-files` tool.
//
// The most common use case is to use CSV or JSONL format for your line. For example, you can
// extract each transaction out of the block as a single line in JSON format as an object. The
// `substream-sink-files` will then package them in a bundle for N blocks.
type Lines struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lines         []string               `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lines) Reset() {
	*x = Lines{}
	mi := &file_sf_substreams_sink_files_v1_files_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lines) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lines) ProtoMessage() {}

func (x *Lines) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_sink_files_v1_files_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lines.ProtoReflect.Descriptor instead.
func (*Lines) Descriptor() ([]byte, []int) {
	return file_sf_substreams_sink_files_v1_files_proto_rawDescGZIP(), []int{0}
}

func (x *Lines) GetLines() []string {
	if x != nil {
		return x.Lines
	}
	return nil
}

var File_sf_substreams_sink_files_v1_files_proto protoreflect.FileDescriptor

const file_sf_substreams_sink_files_v1_files_proto_rawDesc = "" +
	"\n" +
	"'sf/substreams/sink/files/v1/files.proto\x12\x1bsf.substreams.sink.files.v1\"\x1d\n" +
	"\x05Lines\x12\x14\n" +
	"\x05lines\x18\x01 \x03(\tR\x05linesB\x99\x02\n" +
	"\x1fcom.sf.substreams.sink.files.v1B\n" +
	"FilesProtoP\x01ZYgithub.com/streamingfast/substreams-sink-files/pb/sf/substreams/sink/files/v1;pbsinkfiles\xa2\x02\x04SSSF\xaa\x02\x1bSf.Substreams.Sink.Files.V1\xca\x02\x1bSf\\Substreams\\Sink\\Files\\V1\xe2\x02'Sf\\Substreams\\Sink\\Files\\V1\\GPBMetadata\xea\x02\x1fSf::Substreams::Sink::Files::V1b\x06proto3"

var (
	file_sf_substreams_sink_files_v1_files_proto_rawDescOnce sync.Once
	file_sf_substreams_sink_files_v1_files_proto_rawDescData []byte
)

func file_sf_substreams_sink_files_v1_files_proto_rawDescGZIP() []byte {
	file_sf_substreams_sink_files_v1_files_proto_rawDescOnce.Do(func() {
		file_sf_substreams_sink_files_v1_files_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sf_substreams_sink_files_v1_files_proto_rawDesc), len(file_sf_substreams_sink_files_v1_files_proto_rawDesc)))
	})
	return file_sf_substreams_sink_files_v1_files_proto_rawDescData
}

var file_sf_substreams_sink_files_v1_files_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sf_substreams_sink_files_v1_files_proto_goTypes = []any{
	(*Lines)(nil), // 0: sf.substreams.sink.files.v1.Lines
}
var file_sf_substreams_sink_files_v1_files_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sf_substreams_sink_files_v1_files_proto_init() }
func file_sf_substreams_sink_files_v1_files_proto_init() {
	if File_sf_substreams_sink_files_v1_files_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sf_substreams_sink_files_v1_files_proto_rawDesc), len(file_sf_substreams_sink_files_v1_files_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sf_substreams_sink_files_v1_files_proto_goTypes,
		DependencyIndexes: file_sf_substreams_sink_files_v1_files_proto_depIdxs,
		MessageInfos:      file_sf_substreams_sink_files_v1_files_proto_msgTypes,
	}.Build()
	File_sf_substreams_sink_files_v1_files_proto = out.File
	file_sf_substreams_sink_files_v1_files_proto_goTypes = nil
	file_sf_substreams_sink_files_v1_files_proto_depIdxs = nil
}
